---
title: "blog_5"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, options(scipen=999))

library(tidyverse)
library(ggplot2)
library(janitor)
library(geofacet)
library(cowplot)
library(scales)

# read in data
pv <- read.csv("data/popvote_1948-2016.csv")
pv_state <- read.csv("data/popvote_bystate_1948-2016.csv")
ads_2020 <- read.csv("data/ads_2020.csv") %>%
  separate(period_enddate, into = c("year", "month", "day"), sep = "-")
ad_campaigns <- read.csv("data/ad_campaigns_2000-2012.csv") 
ad_creative <- read.csv("data/ad_creative_2000-2012.csv")
pollavg <- read.csv("data/pollavg_1968-2016.csv")
pollavg_st <- read.csv("data/pollavg_bystate_1968-2016.csv")
polls_16 <- read.csv("data/polls_2016.csv")
polls_20 <- read.csv("data/polls_2020.csv")
vep <- read.csv("data/vep_1980-2016.csv")

ads <- ad_campaigns %>%
  left_join(ad_creative)

```

```{r}

# state by state spend

## The State-level Air War in 2008 (Obama vs. McCain)
air_war_map_08 <- ad_campaigns %>%
  mutate(year = as.numeric(substr(air_date, 1, 4))) %>%
  mutate(month = as.numeric(substr(air_date, 6, 7))) %>%
  mutate(state = state.name[match(state, state.abb)]) %>%
  filter(cycle == 2008) %>%
  left_join(pvstate_df %>% filter(year == 2008) %>% select(-year), by="state") %>%
  mutate(winner=ifelse(D_pv2p > R_pv2p, "democrat", "republican")) %>%
  group_by(cycle, state, air_date, party, winner) %>%
  summarise(total_cost = sum(total_cost)) %>%
  filter(!is.na(state)) %>%
  # ggplot(aes(x=air_date, y=log(total_cost+1), color=party)) +
  ggplot(aes(x=party, y=total_cost, fill=party)) +
  geom_bar(stat="identity") +
  geom_rect(aes(fill=winner), xmin=-Inf, xmax=Inf, ymin=46.3*10^6, ymax=52*10^6) +
  facet_geo(~ state, scales="free_x") +
  scale_fill_manual(values = c("blue", "red")) +
  scale_y_continuous(labels = unit_format(unit = "M", scale = 1e-6)) +
  xlab("") + ylab("ad spend") +
  theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())

air_war_map_08

```


```{r}

month_totals <- ad_campaigns %>%
  separate(air_date, into = c("year", "month", "day"), sep = "-") %>%
  group_by(cycle, month, party) %>%
  arrange(month) %>%
  summarize(month_spend = sum(total_cost)) %>%
  ungroup() %>%
  group_by(cycle, party) %>%
  mutate(total_spend = sum(month_spend)) %>%
  ungroup() %>%
  mutate(month_share = month_spend/total_spend) %>%
  rename(year = cycle) %>%
  left_join(pv)

month_totals$month <- month_totals$month %>%
  replace_na("10")



# plot of month-by-month spend totals 2000-2012
month_totals %>%
  ggplot(aes(x = month, y = month_share, fill = party)) +
  scale_fill_manual(values = c("steelblue2", "indianred")) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_wrap(~year) +
  theme_light() +
  labs(title = "Share of Total Political Ad Spend by Month (2000-2012)",
       y = "Share of Total Ad Spend by Month",
       x = "Month",
       fill = "Party")

ggsave("figures/ad_spend_month_share.png")

```

```{r}

# data wrangling from class code
tone_purpose <- ad_creative %>%
  group_by(ad_purpose) %>%
  count(ad_tone) %>%
  mutate(purpose_sum = sum(n)) %>%
  mutate(tone_share = n/purpose_sum) %>%
  ungroup()

tone_purpose
  

tone_purpose %>%
  filter(ad_tone != "other" & ad_tone != "NA" & ad_purpose != "NA") %>%
  ggplot(aes(x = ad_purpose, y = tone_share, fill = ad_tone)) +
  geom_bar(stat = "identity", position = "dodge") +
  theme_light() +
  labs(title = "Tone Distributions Among Political Ad Purposes",
       x = "Ad Purpose",
       y = "Ad Tone Share",
       fill = "Ad Tone") +
  scale_fill_manual(values = c("indianred", "steelblue2", "palegreen4"))

ggsave("figures/ad_tone_by_purpose.png")


```

```{r}

## Tone in Political Ads
ad_campaigns %>%
  left_join(ad_creative) %>%
  filter(ad_tone %in% c("attack", "promote")) %>%
  mutate(year = as.numeric(substr(air_date, 1, 4))) %>%
  mutate(month = as.numeric(substr(air_date, 6, 7))) %>%
  filter(year %in% c(2000, 2004, 2008, 2012), month > 7) %>%
  group_by(cycle, air_date, ad_tone) %>%
  summarise(total_cost = sum(n_stations)) %>%
  group_by(cycle, air_date) %>%
  mutate(total_cost = total_cost/sum(total_cost)) %>%
  ungroup() %>%
  ggplot(aes(x=air_date, y=total_cost, fill=ad_tone, color=ad_tone)) +
  # scale_x_date(date_labels = "%b") +
  scale_fill_manual(values = c("firebrick","palegreen4"), name = "ad tone") +
  scale_color_manual(values = c("firebrick","palegreen4"), name = "ad tone") +
  geom_bar(stat = "identity") +
  facet_wrap(cycle ~ ., scales="free") +
  labs(x = "",
       y = "% of ads bought on day",
       fill = "Ad Tone",
       title = "Ad Tone Over Time",
       subtitle = "2000-2012") +
  theme_light() +
  theme(axis.text.x = element_blank())

ggsave("figures/ad_tone_over_time.png")

```
```{r}

ads_2020 %>%
  summarise(trump_sum = sum(trump_airings), biden_sum = sum(biden_airings)) %>%
  mutate(pct_biden = biden_sum/(biden_sum + trump_sum), pct_trump = trump_sum/(biden_sum + trump_sum))


```

